### ISSUE TITLE
Can't start delayed_job with a named Queue in 0.4.4

### ISSUE THREAD

**Issue by gpavlidi** [collectiveidea/delayed_job_active_record#59]
Steps to reproduce:
`script/delayed_job -i 0 --queue=Stitch run`
or
`Delayed::Backend::ActiveRecord::Job.where(:queue => ["Stitch"])`
Gets me a :
`NoMethodError: undefined method `abstract_class?' for Object:Class`

I managed to track it down in file [active_record.rb#L50](https://github.com/collectiveidea/delayed_job_active_record/blob/master/lib/delayed/backend/active_record.rb#L50)
`ready_scope = ready_scope.where(:queue => Worker.queues) if Worker.queues.any?`

It seems that AR somehow chokes on a where clause with an Array input. Also it works fine in 0.4.3 since it 's using an IN clause instead.

Gem Versions:
- delayed_job (3.0.5)
- delayed_job_active_record (0.4.4)
