### ISSUE TITLE
Error in 4.1.5 when upgrading Rails from 6.0 to 6.1

### ISSUE THREAD

**Issue by vonamann** [collectiveidea/delayed_job_active_record#190]
I have `delayed_job_active_record` v4.5.1 in my project running on Rails 6.0.2.1 which works good.

When I try to upgrade Rails to 6.1 I get an error when running local server:
```
config/initializers/delayed_job.rb:4:in `<class:Job>': undefined method `establish_connection' for Delayed::Backend::ActiveRecord::Job:Class (NoMethodError)
```

My `config/initializers/delayed_job.rb` looks like this. I use another database to store delayed jobs and pass its options within the initializer.
```
class Delayed::Backend::ActiveRecord::Job
  establish_connection(DATABASE_TWO_OPTIONS)
end

Delayed::Worker.destroy_failed_jobs = false
Delayed::Worker.sleep_delay = 3
...
```

When I comment out `establish_connection` line, I get another error:
```
.bundle/ruby/2.6.0/gems/delayed_job_active_record-4.1.5/lib/delayed/backend/active_record.rb:33:in `<module:ActiveRecord>': superclass mismatch for class Job (TypeError)
```

I was able to workaround the problem by adding in the beginning of the initalizer:
```
require 'delayed/backend/active_record'
```

Is this a bug or this `require` is really needed here? Thank you!

**Comment by albus522** [comment]
https://github.com/collectiveidea/delayed_job_active_record/issues/185#issuecomment-743289981

**Comment by albus522** [comment]
https://github.com/collectiveidea/delayed_job_active_record/issues/185#issuecomment-808326919
